---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
  labels:
    app: storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
    spec:
      # nodeSelector:
        # kubernetes.io/hostname: aaltosea-node_name-worker
      containers:
        - name: storage-service
          image: rdsea/fed_storage_service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: EDGE_SERVICE
              value: "edge_service"
            - name: EDGE_SERVICE_PORT
              value: "8006"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name